services:
  cpu:
    image: ros2_rolling_ws
    privileged: true
    network_mode: host
    command: bash
    environment:
      # enable visualization/GUIs
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      # ros networking settings
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      - ROS_STATIC_PEERS
      - ROS_DOMAIN_ID
    volumes:
      # Mount the colcon dev ws (specified as COLCON_WS) into the container.
      # If COLCON_WS is not defined by the user, it will default to /dev/null and no workspace will be mounted.
      - ${COLCON_WS:-/dev/null}:/home/ubuntu/overlay_ws/:rw
      # enable visualization/GUIs
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-$HOME/.Xauthority}:/home/ubuntu/.Xauthority
      # mount ssh keys and gitconfig for running git operations in the container
      - /home/$USER/.ssh:/home/ubuntu/.ssh:ro
      - /home/$USER/.gitconfig:/home/ubuntu/.gitconfig:ro
      - /dev/input:/dev/input
      - /dev/bus/usb:/dev/bus/usb
      # mount the directory with signing keys into the container, if `GPG_DIR` is specified by the user.
      # this is useful for things like signing git commits.
      - ${GPG_DIR:-/dev/null/}:/home/ubuntu/.gnupg:rw
